// <auto-generated />
using System;
using BookSale.Infrastructure.Migrations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookSale.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250116033423_dbinit")]
    partial class dbinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookSale.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_phone");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method_id");

                    b.Property<string>("PaymentOrderId")
                        .HasColumnType("text")
                        .HasColumnName("payment_order_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("BookSale.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("payment_methods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 16, 3, 34, 22, 690, DateTimeKind.Utc).AddTicks(8021),
                            Name = "VNPay",
                            UpdatedAt = new DateTime(2025, 1, 16, 3, 34, 22, 690, DateTimeKind.Utc).AddTicks(8023)
                        });
                });

            modelBuilder.Entity("dotnet_boilerplate.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("roles_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 16, 3, 34, 22, 537, DateTimeKind.Utc).AddTicks(7309),
                            Name = "admin",
                            UpdatedAt = new DateTime(2025, 1, 16, 3, 34, 22, 537, DateTimeKind.Utc).AddTicks(7310)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 16, 3, 34, 22, 537, DateTimeKind.Utc).AddTicks(7312),
                            Name = "member",
                            UpdatedAt = new DateTime(2025, 1, 16, 3, 34, 22, 537, DateTimeKind.Utc).AddTicks(7312)
                        });
                });

            modelBuilder.Entity("dotnet_boilerplate.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_joined");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsStaff")
                        .HasColumnType("boolean")
                        .HasColumnName("is_staff");

                    b.Property<bool>("IsSuperUser")
                        .HasColumnType("boolean")
                        .HasColumnName("is_superuser");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users_user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 16, 3, 34, 22, 690, DateTimeKind.Utc).AddTicks(8009),
                            DateJoined = new DateTime(2025, 1, 16, 3, 34, 22, 690, DateTimeKind.Utc).AddTicks(8010),
                            Email = "admin@email.com",
                            FullName = "Admin",
                            IsActive = true,
                            IsStaff = false,
                            IsSuperUser = true,
                            LastLogin = new DateTime(2025, 1, 16, 3, 34, 22, 690, DateTimeKind.Utc).AddTicks(8010),
                            Password = "$2a$11$RNr.qMwKfGGvdEbUd.PvSuut6YqMPvOk.Wkxd7dmByfUcuAc3zpCq",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 1, 16, 3, 34, 22, 690, DateTimeKind.Utc).AddTicks(8013)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 16, 3, 34, 22, 690, DateTimeKind.Utc).AddTicks(8016),
                            DateJoined = new DateTime(2025, 1, 16, 3, 34, 22, 690, DateTimeKind.Utc).AddTicks(8016),
                            Email = "tien@email.com",
                            FullName = "Tien",
                            IsActive = true,
                            IsStaff = false,
                            IsSuperUser = false,
                            LastLogin = new DateTime(2025, 1, 16, 3, 34, 22, 690, DateTimeKind.Utc).AddTicks(8017),
                            Password = "$2a$11$RNr.qMwKfGGvdEbUd.PvSuut6YqMPvOk.Wkxd7dmByfUcuAc3zpCq",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 1, 16, 3, 34, 22, 690, DateTimeKind.Utc).AddTicks(8018)
                        });
                });

            modelBuilder.Entity("BookSale.Domain.Entities.Order", b =>
                {
                    b.HasOne("BookSale.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("dotnet_boilerplate.Domain.Entities.User", b =>
                {
                    b.HasOne("dotnet_boilerplate.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("dotnet_boilerplate.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
